defaults:
  - _self_
  - env: point_maze
  - encoder: dino
  - action_encoder: proprio
  - proprio_encoder: proprio
  - decoder: vqvae
  - predictor: vit
  - override hydra/launcher: basic

ckpt_base_path: ./

hydra:
  run:
    dir: ${ckpt_base_path}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${ckpt_base_path}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}

training:
  seed: 0
  epochs: 1
  batch_size: 4
  save_every_x_epoch: 1
  reconstruct_every_x_batch: 500
  num_reconstruct_samples: 2
  encoder_lr: 1e-6
  decoder_lr: 3e-4
  predictor_lr: 5e-4
  action_encoder_lr: 5e-4

img_size: 224
frameskip: 5
concat_dim: 1
normalize_action: True
action_emb_dim: 10
num_action_repeat: 1
proprio_emb_dim: 10
num_proprio_repeat: 1
num_hist: 3
num_pred: 1
has_predictor: True
has_decoder: True

model:
  _target_: models.visual_world_model.VWorldModel
  image_size: ${img_size}
  num_hist: ${num_hist}
  num_pred: ${num_pred}
  train_encoder: False
  train_predictor: True
  train_decoder: True

debug: True

plan_settings:
  plan_cfg_path: null
  planner: ['gd', 'cem']
  goal_source: ['dset', 'random_state']
  goal_H: [5]
  alpha: [0.1, 1]
